'use client'

// import type { Metadata } from "next";
import {Inter, Suez_One, Roboto_Slab, Roboto} from 'next/font/google'
import "./globals.css";
import CustomCursor from "./components/CustomCursor/CustomCursor";
import { motion, useScroll } from "framer-motion";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal'],
  variable: '--font-inter'
})

const suezOne = Suez_One({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
  variable: '--font-suze-one'
})

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal'],
  variable: '--font-roboto'
})

const robotoSlab = Roboto_Slab({
  subsets: ['latin'],
  weight: ['300'],
  style: ['normal'],
  variable: '--font-roboto-slab'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { scrollYProgress } = useScroll();

  return (
    <html lang="en" className="bg-[#050505]" suppressHydrationWarning>
      <body suppressHydrationWarning className={`${inter.variable} ${suezOne.variable} ${roboto.variable} ${robotoSlab.variable} bg-[#050505] text-zinc-300 antialiased min-h-screen`}>
        <CustomCursor />
        <motion.div
          className="fixed top-0 left-0 right-0 h-1 bg-gradient-to-r from-cyan-400 to-blue-500 origin-left z-[100] pointer-events-none shadow-[0_0_10px_rgba(34,211,238,0.8)]"
          style={{ scaleX: scrollYProgress }}
        />
        {children}
      </body>
    </html>
  );
}
